# Generated by Django 4.1 on 2022-10-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Villain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=50)),
                ('desc', models.CharField(default=b'I01\n', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='hero',
            name='desc',
            field=models.CharField(default=b'I01\n', max_length=200),
        ),
    ]
